### PR TITLE
Always use https when loading external resources

### PR DESCRIPTION
**Pull request by bamse16**
Loading external resources using //domain.com/resource is an anti-pattern. See
http://www.paulirish.com/2010/the-protocol-relative-url/

### CODE REVIEW

**Comment by benblee** [comment]
A similar request was already submitted and not sure if it was turned down or included and just closed:

https://github.com/WHMCS/templates-six/pull/6

Just leaving the link so things are referenced.

**Comment by bamse16** [comment]
Thanks for pointing that :-).

Did not notice it and since it was not availble in master, I assumed it was not requested before.

Regards,
Marius

**Comment by JRawly** [comment]
We push to this repository as part of our release process, and as a rule don't accept outside code into it. I am therefore going to decline this request at this time. If there is some functional benefit we're overlooking, please don't hesitate to reach out us via www.whmcs.com/support

**Comment by bamse16** [comment]
Hi Joe,

I've only noticed that you're rejecting all the pull requests. I've went through all the requests, and all of them seemed reasonable.

IMHO, WHMCS is losing out by not including these in the default six template.

May I suggest to edit the project README and post the standard "thank you for your contribution, but we have a different process" disclaimer, so we know not to bother? I could send a push request with that change, but I'm afraid that it will be rejected :-).

Regards,
Marius

**Pull request closed without merging**
