### PR TITLE
Encourage SSL use.

### PR DESCRIPTION
**Pull request by DanielDent**

### CODE REVIEW

**Comment by benblee** [comment]
Would the following be a possibility since twitter, and others, will force https on their own:

```
{$LANG.twitterfollowus} @ <a href="//twitter.com/{$twitterusername}" target="_blank">//twitter.com/{$twitterusername}</a> {$LANG.twitterfollowuswhy}
```

**Comment by DanielDent** [comment]
Twitter can't redirect to https if the http request which would redirect to https gets intercepted before it gets to them. The // syntax is typically used to have content load over the same protocol as the initial page, with the idea of having things work when SSL isn't supported. However, in this case, I don't think we need to fear Twitter suddenly deciding to drop SSL support.

**Comment by benblee** [comment]
Thanks for the reply and the explanation!

**Comment by JRawly** [comment]
We push to this repository as part of our release process, and as a rule don't accept outside code into it. I am therefore going to decline this request at this time. If there is some functional benefit we're overlooking, please don't hesitate to reach out us via www.whmcs.com/support

**Pull request closed without merging**
