### PR TITLE
Create translatable label for NEW notifications

### PR DESCRIPTION
**Pull request by cubixgit**
This also needs the inclusion of some kind of $_LANG['notificationsnewlabel'] = "NEW";  in the langs file

Currently we're forced to correct this HTML via JQuery, which is not good

### CODE REVIEW

**Comment by cubixgit** [comment]
Don't know where to suggest the new $LANG as the code requires. Please consider this change.

**Comment by JRawly** [comment]
Hello cubixgit,

As has been indicated in some previous pull requests, we intend for this to be a read only repository. We have automated deployment tools that sync it from our main product repository. So I am going to close this PR without merging it.

For issues such as this you can open a ticket with our support team who will be able to open a case to get them resolved. As such, I have opened case CORE-12509 to resolve this.

**Comment by cubixgit** [comment]
Thank you. Can you provide any link to follow this core 12509 ?



On July 6, 2018 1:49:36 PM UTC, JRawly <notifications@github.com> wrote:
>Hello cubixgit,
>
>As has been indicated in some previous pull requests, we intend for
>this to be a read only repository. We have automated deployment tools
>that sync it from our main product repository. So I am going to close
>this PR without merging it.
>
>For issues such as this you can open a ticket with our support team who
>will be able to open a case to get them resolved. As such, I have
>opened case CORE-12509 to resolve this.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/WHMCS/templates-six/pull/21#issuecomment-403039952

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JRawly** [comment]
Unfortunately no. It's an internal tracker. However you can keep an eye on the change log when releases are made for a list of included cases. https://changelog.whmcs.com

**Pull request closed without merging**
